# Generated by Django 3.2.4 on 2021-07-30 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('complaints', '0002_remove_complaint_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='complaint',
            name='resoultion',
        ),
        migrations.RemoveField(
            model_name='complaint',
            name='status',
        ),
        migrations.AlterField(
            model_name='complaint',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
